### ISSUE TITLE
Bug when using M2

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/AMLGoldStandardGenerator#18]
Exception in thread "main" java.lang.NullPointerException at edu.bonn.AMLGoldStandardGenerator.aml.Impl.GenerateAML.getCaexElementsSplit(GenerateAML.java:49)
	at main.AMLGoldStandardGenerator.generateFiles(AMLGoldStandardGenerator.java:328)
	at main.AMLGoldStandardGenerator.main(AMLGoldStandardGenerator.java:374)

`HeterogeneityExampleData/AutomationML/Single-Heterogeneity/M2/Testbeds-1/`

**Comment by igrangel** [comment]
The file seed.aml was missing in the `Testbeds-1` folder
